language: csharp
mono: none
dist: xenial
dotnet: 2.2
script:
- >
  dotnet publish
    --output $PWD/speedtest
    --configuration release
    $PWD/src/Stubias.SpeedTest.Client/Stubias.SpeedTest.Client.csproj
- tar -cjvf speedtest.tar.bz2 speedtest

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: speedtest.tar.bz2
  skip_cleanup: true
  on:
    repo: aburgett87/Stubias.SpeedTest.Client
    tags: true

cache:
  directories:
  - "$HOME/.nuget/packages"
  - "$HOME/.local/share/NuGet/Cache"