language: csharp
services:
  - docker
mono: none
dist: xenial
dotnet: 2.2
script:
  - dotnet publish -o $PWD/speedtest $PWD/src/Stubias.SpeedTest.Client/Stubias.SpeedTest.Client.csproj
  - tar -cjvf speedtest.tar.bz2 speedtest

cache:
  directories:
    - '$HOME/.nuget/packages'
    - '$HOME/.local/share/NuGet/Cache'